# Numpy

In [4]:
!pip install numpy

In [3]:
import numpy as np

### create array using numpy

In [4]:
arr1 = np.array([1 , 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

### shape of an array

In [7]:
arr1 = np.array([1 , 2, 3, 4, 5])
arr1.shape

(5,)

### Converting it into the 2-D array 

In [9]:
arr1 = np.array([1 , 2, 3, 4, 5])
arr1 = arr1.reshape(1 , 5) #converting 1d -> 2d
arr1.shape #Here we can see that the shape of the array is 2D where row = 1 , column = 5

(1, 5)

In [11]:
arr1 = np.array([[1 , 2, 3, 4, 5] , ['e' ,4, 'j' , 4 , 'abc']])
print(arr1)
arr1.shape

[['1' '2' '3' '4' '5']
 ['e' '4' 'j' '4' 'abc']]


(2, 5)

### Creating arrays with inbuilt function

##### creating an array with containing [0 , 10) elements after the increment of the 2 

In [13]:
np.arange(0 , 10 , 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0 , 10 , 1).reshape(1 , 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
np.arange(0 , 10 , 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.arange(0 , 10 , 2).reshape(5,2)

ValueError: cannot reshape array of size 5 into shape (5,2)

In [74]:
np.arange(0 , 10 , 2).reshape(5,1).shape


(5, 1)

### inbuilt array function 

In [79]:
#creating a 2d array with row = 3 , column = 4 , but elements are by default float
np.ones((3 , 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
#creating a 2d array with row = 3 , column = 4 , each element is integer
np.ones((3 , 4) , dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Attributes of Numpy array

In [25]:
arr = np.array([[1 , 2 , 3] , [4 , 5, 6]])
arr_2= np.array(["abc" , 1 , 2, 3])
print('array :' , arr)
print('shape :' , arr.shape)
print("number of dimension :" , arr.ndim)
print('size (no. of elements):' , arr.size)
print('Data type :' , arr.dtype)
print('Data type :' , arr_2.dtype)
print('Item size(in bytes) :' , arr.itemsize)

array : [[1 2 3]
 [4 5 6]]
shape : (2, 3)
number of dimension : 2
size (no. of elements): 6
Data type : int64
Data type : <U21
Item size(in bytes) : 8


### Identity matrix

In [91]:
np.eye(3 , dtype = int) # diagonal element should be 1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Vectorized Operations

In [28]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,52])

### Element wise addition

In [30]:
print("addition: " , arr1+arr2) # size of the arrays must be same during this

addition:  [11 22 33 44 57]


In [32]:
print("subtraction: " , arr1-arr2)

subtraction:  [ -9 -18 -27 -36 -47]


In [34]:
print("multiplication: " , arr1*arr2)

multiplication:  [ 10  40  90 160 260]


In [44]:
print("division: " , arr1/arr2)

division:  [0.1        0.1        0.1        0.1        0.09615385]


### Universal function

In [47]:
arr = np.array([1,2,3,4,5,6])

### square root

In [51]:
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


### Exponential

In [53]:
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


### Sine

In [57]:
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


### All this operation are element specific operation , we can apply it on the particular value also rather than array

In [62]:
print(np.sin(5))

-0.9589242746631385


In [64]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array slicing and Indexing

#Array slicing syntax : 
arr[rowStartIndex : rowEndIndex , colStartIndex:colEndIndex]
It will go row-wise rowStartIndex to rowEndIndex-1 and simultaneously
it will print the array elements of  each row starting from the colStartIndex to colEndIndex-1

In [32]:
arr = np.array([[1,2,3,4,5] , [4,2,3,4,5] , [8,4,5,2,6]])
arr

array([[1, 2, 3, 4, 5],
       [4, 2, 3, 4, 5],
       [8, 4, 5, 2, 6]])

#### Accessing single element from the array : 

In [79]:
arr[0]

array([1, 2, 3, 4, 5])

In [85]:
arr[0][4]

np.int64(5)

In [87]:
arr[1:] # This prints the two row from rowIndex = 1 to rowIndex = 2 (0-based indexing)

array([[4, 2, 3, 4, 5],
       [8, 4, 5, 2, 6]])

In [97]:
print(arr[1:2])
"""similar to the slicing we do on the normal array where say [x:y] it 
prints the from  rowIndex =x to rowIndex y-1"""

[[4 2 3 4 5]]


'similar to the slicing we do on the normal array where say [x:y] it \nprints the from  rowIndex =x to rowIndex y-1'

In [99]:
arr[1: , 2:]  # it prints from rowIndex = 1 till the last rowIndex and colIndex = 2 till the last colIndex

array([[3, 4, 5],
       [5, 2, 6]])

In [101]:
arr[1:3 , 2:4] #it prints from rowIndex = 1 to rowIndex = 2 && colIndex = 2 to colIndex = 3

array([[3, 4],
       [5, 2]])

### Modify array elements

In [107]:
print(arr)

[[1 2 3 4 5]
 [4 2 3 4 5]
 [8 4 5 2 6]]


In [113]:
arr[1 , 2] = 100
arr

array([[ 99,   2,   3,   4,   5],
       [  4,   2, 100,   4,   5],
       [  8,   4,   5,   2,   6]])

In [111]:
arr[0][0]  = 99
arr

array([[99,  2,  3,  4,  5],
       [ 4,  2,  3,  4,  5],
       [ 8,  4,  5,  2,  6]])

### replacing all the elements with single elements after particular row

In [116]:
arr[2:] = 5999
print(arr)

[[  99    2    3    4    5]
 [   4    2  100    4    5]
 [5999 5999 5999 5999 5999]]


In [34]:
print(arr)
arr[1: , 2:] = 11111
print(arr)

[[1 2 3 4 5]
 [4 2 3 4 5]
 [8 4 5 2 6]]
[[    1     2     3     4     5]
 [    4     2 11111 11111 11111]
 [    8     4 11111 11111 11111]]


### Statistical concepts -- Normalization

Normalization is a method of converting the data such that you mean of the data is 0 and  standard deviation is 1

In [130]:
#calculate the mean and standard deviation : 
data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
std_dev = np.std(data)

#Normalize the data
normalized_data = (data-mean) / std_dev
print("Normalized data: ",normalized_data)

print("mean: ", np.mean(normalized_data))
print("std_dev:" , np.std(normalized_data))


Normalized data:  [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]
mean:  -6.661338147750939e-17
std_dev: 1.0


In [134]:
### Statistical Operations : 
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print("mean :" , mean)

#Standard Deviation
std_dev = np.std(data)
print("standard deviation: " , std_dev)

#Median
median = np.median(data)
print("median: " , median)

#Variance
variance = np.var(data)
print("variance: " , variance)


mean : 5.5
standard deviation:  2.8722813232690143
median:  5.5
variance:  8.25


###  Logical operation

In [137]:
data = np.array([1,3,4,5,6,7,8,9,10])
data > 5 # basically it is checking how many values are greater than 5

array([False, False, False, False,  True,  True,  True,  True,  True])

##### How to print those values : 

In [140]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [142]:
data[(data>=5) & (data <= 7) ]

array([5, 6, 7])